version: '3.8'

networks:
  voting-app-net:
    driver: bridge

services:
  frontend:
    build: ./frontend            # Looks inside the frontend folder for the Nginx Dockerfile
    container_name: voting-frontend
    ports:
      - "5000:80"                # Maps host port 5000 to container port 80
    networks:
      - voting-app-net
    depends_on:
      - backend

  backend:
    build: ./backend             # Looks inside the backend folder for the Python Dockerfile
    container_name: voting-backend
    expose:
      - "5000"                   # Opens port 5000 internally to the frontend
    environment:
      - FLASK_ENV=development
    networks:
      - voting-app-net
